export const PLANT_TYPE = {
  LEAF_CROP: "LEAF_CROP",
  FRUIT_CROP: "FRUIT_CROP",
};

export const PLANT_TYPE_MAP = {
  [PLANT_TYPE.LEAF_CROP]: "Leaf Crop",
  [PLANT_TYPE.FRUIT_CROP]: "Fruit Crop",
};

export const PLANT_STATUS = {
  STATUS_CREATED: "CREATED",
  STATUS_ACTIVATED: "ACTIVATED",
  STATUS_HARVESTED: "HARVESTED",
  STATUS_DEACTIVATED: "DEACTIVATED"
}

export const PLANT_STATUS_MAP = {
  [PLANT_STATUS.STATUS_CREATED]: "Created",
  [PLANT_STATUS.STATUS_ACTIVATED]: "Activated",
  [PLANT_STATUS.STATUS_HARVESTED]: "Harvested",
  [PLANT_STATUS.STATUS_DEACTIVATED]: "Deactivated",
};

export const PLANT_GROWTH = {
  VEGETATIVE: "VEGETATIVE",
  GENERATIVE: "GENERATIVE",
};

export const PLANT_GROWTH_MAP = {
  [PLANT_GROWTH.VEGETATIVE]: "Vegetative",
  [PLANT_GROWTH.GENERATIVE]: "Generative",
};